import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  ProvidersChakra,
  ProvidersPersistRedux,
  ProvidersProgress,
  ProvidersRedux,
  Tostifycontainer,
} from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trello Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ProvidersProgress>
          <Tostifycontainer />
          <ProvidersRedux>
            <ProvidersPersistRedux>
              <ProvidersChakra>
                <>{children}</>
              </ProvidersChakra>
            </ProvidersPersistRedux>
          </ProvidersRedux>
        </ProvidersProgress>
      </body>
    </html>
  );
}
